### ISSUE TITLE
about project.

### ISSUE THREAD

**Issue by zurkes** [Neumi/open_echo#1]
lucky fish finder is already a working product. what is the purpose of this project?

**Comment by jkknibbe99** [comment]
> lucky fish finder is already a working product. what is the purpose of this project?

I could see it being useful to get the depth data on to another device such as a laptop. There, the data can be stored and plotted to create [depth maps](https://photos.bwca.com/m/MAD_ANGLER-190218-142152.JPG) or other similar charts.

**Comment by Neumi** [comment]
Thanks @zurkes for the issue. The video in the readme should explain it.
But the goal is to build an open source echo sounder hardware and software that can be adapted to your use cases and also readable by common hardware like Arduino or similar.
The Lucky Fish Finder is a working product you can buy, but you normally can't read it using an Arduino or computer backend.
I needed a readable sonar hardware for this project: https://github.com/Neumi/3D_water_depth_logger
And because Arduino-readable hardware is either very expensive or hard to get, I thought it might be worthwhile building it myself.
